[user]
email = "88557639+lishaduck@users.noreply.github.com"
name = "Eli"

[core]
fsmonitor = "watchman"

[core.watchman]
register_snapshot_trigger = true

[ui]
conflict-marker-style = "git"
default-command = "log"
editor = "code --wait"
merge-editor = "vscode"
pager = ":builtin"

[git]
push-bookmark-prefix = "lishaduck/push-"

[signing]
backend = "gpg"
key = "8B519052EC19B519D4A41EB052EC979CFC20CA70" # TODO: Remove, will be inferred in 0.28.0
signing.behavior = "own"
