[user]
email = "88557639+lishaduck@users.noreply.github.com"
name = "Eli"

[fsmonitor]
backend = "watchman"

[fsmonitor.watchman]
register-snapshot-trigger = true

[ui]
conflict-marker-style = "git"
default-command = "log"
editor = "code --wait"
merge-editor = "vscode"
pager = ":builtin"

[templates]
git_push_bookmark = '"lishaduck/push-" ++ change_id.short()'

[signing]
backend = "gpg"
key = "A8D589F533725B67"
signing.behavior = "own"

[git]
colocate = true
