#!/usr/bin/env bash
set -e;
shopt -s strict:all 2>/dev/null || true

CONFIG="install.conf.yaml";
DOTBOT_DIR="dotbot";

DOTBOT_BIN="bin/dotbot";
declare BASEDIR_
BASEDIR_="$(dirname "${BASH_SOURCE[0]}")"
declare BASEDIR
BASEDIR="$(cd "${BASEDIR_}" && pwd)";

cd "${BASEDIR}";
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive;
git submodule update --init --recursive "${DOTBOT_DIR}";

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-brew -c "${CONFIG}" "${@}";
