# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# set -g @plugin 'Ataraxy-Labs/opensessions' # LLMs are opt-in.

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '$HOMEBREW_PREFIX/opt/tpm/share/tpm/tpm'
