# https://www.webpro.nl/articles/getting-started-with-dotfiles

# Use code by default, but don't override if already exists
: "${EDITOR:=code}"
: "${VISUAL:=${EDITOR}}"
export EDITOR VISUAL

export BROWSER="chrome"
export PAGER="less -FRX"

# XDG Base Directory Specification (https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
export XDG_HOME_DIR="$HOME"
export ZPFX="$XDG_HOME_DIR/.local"
export XDG_CACHE_HOME="$XDG_HOME_DIR/.cache"
export XDG_CONFIG_HOME="$XDG_HOME_DIR/.config"
export XDG_DATA_HOME="$ZPFX/share"
export XDG_STATE_HOME="$ZPFX/state"
export XDG_BIN_HOME="$ZPFX/bin"

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8"

export CARGO_HOME="$XDG_HOME_DIR/.cargo"

# Configure Rust
case ":${PATH}:" in
  *:"{CARGO_HOME/bin}":*)
    ;;
  *)
    export PATH="{CARGO_HOME/bin}:$PATH"
    ;;
esac
